version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.2

jobs:
    sonar:
        docker:
        - image: 'node:latest'
        steps:
        - checkout
        - sonarcloud/scan
    build:
        docker:
            - image: node:12.20.1-stretch-slim
        steps:
            - checkout
            - run:
                name: install node modules
                command: npm install
            - run:
                name: Install zip
                command: |
                    apt-get update
                    apt-get install zip -y
            - run:
                name: zip and save source code
                command: zip -r function.zip index.js s3-topic-map.json node_modules
            - persist_to_workspace:
                root: ./
                paths: 
                    - function.zip
    deploy:
        docker:
            - image: hashicorp/terraform:light
        steps:
            - checkout
            - attach_workspace:
                at: ./IAC
            - run:
                name: Terraform init
                command: |
                    cd IAC &&
                    terraform init
            - run:
                name: Terraform provide and deploy
                command: |
                    cd IAC &&
                    terraform apply -auto-approve

workflows:
    main:
        jobs:
            - sonar
            - build:
                requires: 
                    - sonar
            - deploy:
                context: 
                    - TerraformContext
                requires: 
                    - build
                filters:
                    branches:
                        only:
                            - master
                            - qa
            
